apiVersion: apps/v1
kind: Deployment
metadata:
  name: formation-demo1
  labels:
    app: formation-demo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: formation-demo1
  template:
    metadata:
      labels:
        app: formation-demo1
    spec:
      containers:
        - name: formation-demo1
          image: projetsir2022/groupe6:latest
          ports:
            - containerPort: 8080
